version: '3'
services:
  session:
    build: 'net.whisper.session'
    networks:
      - whispernet
    hostname: session.whisper.net
    container_name: session
    depends_on:
      - broker
  wssession:
    build: 'net.whisper.wssession'
    networks:
      - whispernet
    hostname: wssession.whisper.net
    container_name: wssession
    depends_on:
      - broker
  gateway:
    build: './nginx'
    ports:
      - '80:80'
    networks:
      - whispernet
    hostname: gateway.whisper.net
    container_name: gateway
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - whispernet
    hostname: zookeeper.whisper.net
  broker:
    depends_on:
      - zookeeper
    build: './broker'
    container_name: broker
    networks:
      - whispernet
    hostname: broker.whisper.net
  cache:
    build: './redis'
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
    networks:
      - whispernet
  wsserver:
    build: './signal-server'
    networks:
      - whispernet
  frontend:
    build:
      context: './ui'
      dockerfile: './web/Dockerfile'
    networks:
      - whispernet
    hostname: frontend.whisper.net
    container_name: frontend
networks:
  whispernet:
    driver: 'bridge'
volumes:
  cache:
    driver: local
  kafka:
    driver: local