version: '3'
services:
  loki:
    build: 'loki'
    container_name: loki
    volumes:
      - './loki/data:/data'
    hostname: loki.whisper.net
    networks:
      - whispernet
  grafana:
    build: 'grafana'
    hostname: grafana.whisper.net
    container_name: grafana
    volumes:
      - './grafana/data:/var/lib/grafana'
    ports:
      - "3000:3000"
    depends_on:
      - loki
  promtail:
    build: 'promtail'
    hostname: promtail.whisper.net
    container_name: promtail
    volumes:
      - "./promtail/logs:/var/log"
    networks:
      - whispernet
    depends_on:
      - loki
  session:
    build: 'net.whisper.session'
    networks:
      - whispernet
    hostname: session.whisper.net
    container_name: session
    depends_on:
      - broker
      - gateway
  wssession:
    build: 'net.whisper.wssession'
    networks:
      - whispernet
    hostname: wssession.whisper.net
    container_name: wssession
    depends_on:
      - broker
      - session
  gateway:
    build: './nginx'
    ports:
      - '8099:80'
      - '8098:443'
    networks:
      - whispernet
    hostname: gateway.whisper.net
    container_name: gateway
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - whispernet
    hostname: zookeeper.whisper.net
  broker:
    depends_on:
      - zookeeper
    build: './broker'
    container_name: broker
    networks:
      - whispernet
    hostname: broker.whisper.net
  cache:
    build: './redis'
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
    networks:
      - whispernet
  wsserver:
    depends_on:
      - broker
      - wssession
    build: './signal-server'
    networks:
      - whispernet
  coturn:
    build: './coturn'
    hostname: coturn
    depends_on:
      - wsserver
    networks:
      whispernet:
        ipv4_address: 172.18.0.10
    container_name: coturn
    ports:
      - "3478:3478/udp"            # STUN dostępny na host:3478
      - "3478:3478/tcp"            # TURN dostępny na host:3478
      - "5349:5349/udp"            # TURN z TLS dostępny na host:5349
      - "5349:5349/tcp"            # TURN z TLS dostępny na host:5349
networks:
  whispernet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  cache:
    driver: local
  kafka:
    driver: local
