services:
  loki:
    build:
      context: './MonitoringLoki'
      dockerfile: './Dockerfile.dev'
    container_name: loki
    volumes:
      - loki:/data
    hostname: loki
    networks:
      - whispernet
  grafana:
    build:
      context: './MonitoringGrafana'
      dockerfile: './Dockerfile.dev'
    hostname: grafana
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - whispernet
  promtail:
    build:
      context:  './MonitoringPromtail'
      dockerfile: './Dockerfile.dev'
    hostname: promtail.whisper.net
    container_name: promtail
    volumes:
      - kafka-log:/var/log/external/kafka:ro
      - nginx-log:/var/log/external/nginx:ro
    networks:
      - whispernet
    depends_on:
      - loki
  user-session:
    build:
      context: './UserSession'
      dockerfile: './Dockerfile.dev'
    networks:
      - whispernet
    hostname: user-session
    container_name: user-session
    depends_on:
      - broker
      - gateway
      - loki
  session:
    build:
      context: './Session'
      dockerfile: './Dockerfile.dev'
    networks:
      - whispernet
    hostname: wssession
    container_name: wssession
    depends_on:
      - broker
      - user-session
      - loki
  session-cache:
    build:
      context: './SessionCache'
      dockerfile: './Dockerfile.dev'
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - session-cache:/data
    networks:
      - whispernet
  security-db:
    build:
      context: './SecurityDatabase'
      dockerfile: './Dockerfile.dev'
    hostname: security-db
    container_name: security-db
    networks:
      - whispernet-security
    volumes:
      - security-db:/var/lib/mysql
    ports:
      - 3307:3306
  security:
    build:
      context: 'Security'
      dockerfile: './Dockerfile.dev'
    networks:
      - whispernet-security
    hostname: security
    container_name: security
    depends_on:
      - broker
      - loki
  security-cache:
    build:
      context: './SecurityCache'
      dockerfile: './Dockerfile.dev'
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - security-cache:/data
    networks:
      - whispernet-security
    ports:
      - '6379:6379'
  ws-signal-server:
    depends_on:
      - broker
      - session
    build:
      context: './WebSocketSignalServer'
      dockerfile: './Dockerfile.dev'
    networks:
      - whispernet
  ws-approving-server:
    depends_on:
      - broker
      - session
    build:
      context: './WebSocketApprovingServer'
      dockerfile: './Dockerfile.local'
    container_name: ws-approving
    hostname: ws-approving
    networks:
      - whispernet
  gateway:
    build:
      context: './Gateway'
      dockerfile: './Dockerfile.dev'
    ports:
      - '8099:80'
      - '8098:443'
    networks:
      - whispernet-security
      - whispernet
      - whispernet-cms
    hostname: gateway.whisper.net
    container_name: gateway
    volumes:
      - './Gateway/nginx.conf:/etc/nginx/nginx.conf'
      - nginx-log:/var/log/nginx
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - whispernet
    hostname: zookeeper
  broker:
    depends_on:
      - zookeeper
    build:
      context: './Broker'
      dockerfile: 'Dockerfile.dev'
    container_name: broker
    user: "1000:1000"
    volumes:
      - kafka-log:/var/log/kafka:z
    networks:
      - whispernet
      - whispernet-security
    hostname: broker
  gateway-cms:
    build:
      context: './CmsGateway'
      dockerfile: './Dockerfile.dev'
    ports:
      - '9099:80'
      - '9098:443'
    networks:
      - whispernet-cms
    hostname: gateway-cms
    container_name: gateway-cms
    volumes:
      - './CmsGateway/nginx.conf:/etc/nginx/nginx.conf'
  cms:
    build:
      dockerfile: 'Cms/Dockerfile.example.dev'
    hostname: cms
    container_name: cms
    networks:
      - whispernet-cms
    volumes:
      - './Cms/project-root:/var/www/html'
  cms-db:
    build:
      context: './CmsDatabase'
      dockerfile: './Dockerfile.dev'
    hostname: cms-db
    container_name: cms-db
    networks:
      - whispernet-cms
    volumes:
      - cms-db:/var/lib/mysql
    ports:
      - 3306:3306
networks:
  whispernet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  whispernet-cms:
    driver: bridge
    ipam:
      config:
        - subnet: 173.19.0.0/28
  whispernet-security:
    driver: bridge
    ipam:
      config:
        - subnet: 174.19.0.0/28
volumes:
  security-cache:
    driver: local
  security-db:
    driver: local
  session-cache:
    driver: local
  kafka:
    driver: local
  kafka-log:
    driver: local
  nginx-log:
    driver: local
  cms-db:
    driver: local
  grafana:
    driver: local
  loki:
    driver: local
