version: '3'
services:
  loki:
    build:
      context: './loki'
      dockerfile: 'Dockerfile.qa'
    container_name: loki
    volumes:
      - './loki/data:/data'
    hostname: loki.whisper.net
    networks:
      - whispernet
  grafana:
    build:
      context: './grafana'
      dockerfile: './Dockerfile.qa'
    hostname: grafana.whisper.net
    container_name: grafana
    volumes:
      - './grafana/data-grafana-qa:/var/lib/grafana'
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - whispernet
  promtail:
    build:
      context: 'promtail'
      dockerfile: 'Dockerfile.qa'
    hostname: promtail.whisper.net
    container_name: promtail
    volumes:
      - kafka-log:/var/log/external/kafka:ro
      - nginx-log:/var/log/external/nginx:ro
    networks:
      - whispernet
    depends_on:
      - loki
  session:
    build:
      context: 'net.whisper.session'
      dockerfile: 'Dockerfile.qa'
    networks:
      - whispernet
    hostname: session.whisper.net
    container_name: session
    depends_on:
      - broker
      - gateway
      - loki
  wssession:
    build:
      context: 'net.whisper.wssession'
      dockerfile: './Dockerfile.qa'
    networks:
      - whispernet
    hostname: wssession.whisper.net
    container_name: wssession
    depends_on:
      - broker
      - session
      - loki
  security:
    build:
      context: 'net.whisper.security'
      dockerfile: './Dockerfile.qa'
    networks:
      - whispernet-security
    hostname: security.whisper.net
    container_name: security
    depends_on:
      - broker
      - loki
  gateway:
    build:
      context: './nginx'
      dockerfile: './Dockerfile.qa'
    ports:
      - '8099:80'
      - '8098:443'
    networks:
      - whispernet
      - whispernet-cms
      - whispernet-ui
      - whispernet-security
    hostname: gateway.whisper.net
    container_name: gateway
    volumes:
      - nginx-log:/var/log/nginx
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - whispernet
    hostname: zookeeper.whisper.net
  broker:
    depends_on:
      - zookeeper
    build:
      context: './broker'
      dockerfile: './Dockerfile.qa'
    container_name: broker
    volumes:
      - kafka-log:/var/log/kafka:z
    networks:
      - whispernet-security
      - whispernet
    hostname: broker.whisper.net
  cache-security:
    build:
      context: './redis-security'
      dockerfile: './Dockerfile.qa'
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - redis-security:/data
    networks:
      - whispernet-security
  cache:
    build:
      context: './redis'
      dockerfile: './Dockerfile.qa'
    restart: always
    volumes:
      - cache:/data
    networks:
      - whispernet
  wsserver:
    depends_on:
      - broker
      - wssession
    build:
      context: './signal-server'
      dockerfile: './Dockerfile.qa'
    networks:
      - whispernet
  coturn:
    build:
      context: './coturn'
      dockerfile: './Dockerfile.local'
    hostname: coturn
    depends_on:
      - wsserver
    networks:
      whispernet:
        ipv4_address: 172.18.0.10
    container_name: coturn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
  app-db:
    build:
      context: './app-db'
      dockerfile: './Dockerfile.qa'
    hostname: app-db.whisper.net
    container_name: app-db
    networks:
      - whispernet-security
    volumes:
      - './app-db/app-data:/var/lib/mysql'
  cms-db:
    build:
      context: './cms-db'
      dockerfile: './Dockerfile.qa'
    hostname: cms-db.whisper.net
    container_name: cms-db
    networks:
      - whispernet-cms
    volumes:
      - './cms-db/cms-qa-data:/var/lib/mysql'
  cms:
    build:
      context: './cms'
      dockerfile: './Dockerfile.qa'
    hostname: cms.whisper.net
    container_name: cms
    networks:
      - whispernet-cms
  frontend:
    build:
      context: './ui'
      dockerfile: './web/Dockerfile.qa'
    networks:
      - whispernet-ui
    hostname: frontend.whisper.net
    container_name: frontend
  cms-ui:
    build:
      context: './ui'
      dockerfile: './cms-ui/Dockerfile.qa'
    networks:
      - whispernet-ui
    hostname: cms-ui.whisper.net
    container_name: cms-ui
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer.whisper.net
    restart: always
    networks:
      - whispernet-admin
    ports:
      - "9000:9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - portainer-data:/data
networks:
  whispernet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  whispernet-cms:
    driver: bridge
    ipam:
      config:
        - subnet: 173.19.0.0/28
  whispernet-security:
    driver: bridge
    ipam:
      config:
        - subnet: 174.19.0.0/28
  whispernet-ui:
    driver: bridge
    ipam:
      config:
        - subnet: 175.19.0.0/16
  whispernet-admin:
    driver: bridge
    ipam:
      config:
        - subnet: 176.19.0.0/16
volumes:
  redis-security:
    driver: local
  cache:
    driver: local
  kafka:
    driver: local
  portainer-data:
    driver: local
  kafka-log:
    driver: local
  nginx-log:
    driver: local