import Navigation from "@/app/components/navigation/Navigation";
import StoreProvider from "@/app/StoreProvider";
import {Layout} from "../../../shared/layout/Layout";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  style={{ width: '100%', maxWidth: '100%', minWidth: '100%', height: '100%', minHeight: '100%', maxHeight: '100%' }}>
      <body style={{ width: '100%', maxWidth: '100%', minWidth: '100%', height: '100%', minHeight: '100%', maxHeight: '100%', display: 'flex', flexDirection: 'column' }}>
      <StoreProvider>
      <Layout>
          <Navigation />
          {children}
      </Layout>
      </StoreProvider>
      </body>
    </html>
  )
}
