import Navigation from "@/app/components/navigation/Navigation";
import StoreProvider from "@/app/StoreProvider";
import {Layout} from "../../../shared/layout/Layout";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <StoreProvider>
      <Layout>
          <Navigation />
          {children}
      </Layout>
      </StoreProvider>
      </body>
    </html>
  )
}
