FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN npm install typescript -g
RUN npm install
RUN tsc

FROM node:20-alpine as run
WORKDIR /app
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app
CMD ["node", "./app.js"]