FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN npm install \
&& npm run build \
&& npm prune --production

FROM node:20-alpine AS run
ENV NODE_ENV=production

WORKDIR /app
COPY --from=build /app/package*.json /app/
COPY --from=build /app/dist /app
RUN npm audit fix && npm install --only=production \
&& addgroup -S yourGroup && adduser -S yourUser -G yourGroup \
&& chown yourUser:yourGroup /app -R
USER nodeUser
CMD ["node", "./app.js"]
