FROM nginx:alpine

COPY ./server.crt /etc/nginx/certs/server.crt
COPY ./server.key /etc/nginx/certs/server.key
COPY ./nginx.local-frontend.conf /etc/nginx/nginx.conf
COPY ./fastcgi-symfony.conf /etc/nginx/snippets/fastcgi-symfony.conf
COPY ./error-pages /var/www/html/whispernet-cms/errors

EXPOSE 9099:80
EXPOSE 9098:443
CMD ["nginx", "-g", "daemon off;"]
