FROM node:22

WORKDIR /app
COPY ./package.json ./package.json
RUN npm install
COPY ./cms-ui ./web
COPY ./cms-ui/.env.frontend ./web/.env
COPY ./cms-ui/next.config.docker.mjs /web/next.config.mjs
COPY ./shared ./shared

WORKDIR /app/web

RUN npm install && npm run build


CMD ["npm","run","start"]