FROM node:22  AS buildApp

WORKDIR /app
COPY ./package.json ./package.json
RUN npm install
COPY ./web ./web
COPY ./shared ./shared
COPY ./web/.env.local-frontend ./web/.env
COPY ./shared/config/config.prod.ts ./shared/config/config.ts
RUN cd web \
&& npm install \
&& npm run build

FROM nginx:latest AS deployApp
COPY --from=buildApp /app/web/dist /usr/share/nginx/html
COPY  ./web/nginx.conf /etc/nginx/nginx.conf
