export enum EWebSocketEventType  {
    Offer = 'offer',
    IncommingOffer = 'incomming_offer',
    Answer = 'answer',
    Candidate = 'candidate',
    Waiting = 'waiting',
    Found = 'found',
    Init = 'init',
    InitAccepted = 'init-accepted',
    Join = 'join',
    ICERequest = 'ice-request',
    ICEResponse = 'ice',
    ICEAccepted = 'ice-accepted',
    RoleRequest = 'role-request',
    RoleResponse = 'role-response',
    RoleAccepted = 'role-accepted',
    PrepareRTC = 'prepare-rtc',
    Ready = 'ready',
    Start = 'start',
    Connect = 'connect',
    Connected = 'connected',
    PeerReady = 'peer-ready',
    PeerJoin = 'peer-join',
    Listen = 'listen',
    MsgReceived = 'msg-received',
    ConnectionClose = 'connection-close',
    Retry = 'retry',
    ReconnectSignal = 'reconnect-signal',
    Ping = 'ping',
    Pong = 'pong',
    Auth = 'auth',
    Authorized = 'authorized',
    Unauthorized = 'unauthorized'

}
